# fly.toml app configuration file generated for librechat-otied on 2023-12-11T19:51:40+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "librechat-otied"
primary_region = "sin"

[build]

[http_service]
  internal_port = 3080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
