name: Docker Custom Images Build

on:
  workflow_dispatch:
  push:
    branches:
      - custom-features
    paths:
      - 'api/**'
      - 'client/**'
      - 'packages/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker images
        run: |
          cp .env.example .env
          docker build -f Dockerfile -t ${{ secrets.DOCKERHUB_USERNAME }}/librechat:latest .

      - name: Push images to Docker Hub
        run: |
          docker tag librechat:latest ${{ secrets.DOCKERHUB_USERNAME }}/librechat:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/librechat:latest
